import {PropertyItem} from "@/types/property";

export const mockProperties: PropertyItem[] = [
  {
    id: "1",
    imageUrl: "https://images.unsplash.com/photo-1505691723518-36a5ac3b2d20?q=80&w=1200",
    title: "Vista Mar Premium",
    city: "Florianópolis",
    state: "SC",
    country: "Brasil",
    pricePerNight: 480,
    rating: 4.7,
    reviewsCount: 132,
    type: "apartment",
    isAvailable: true,
    bedrooms: 2,
    guests: 4,
    amenities: ["Wi-Fi", "Piscina", "Ar-condicionado"]
  },
  {
    id: "2",
    imageUrl: "https://images.unsplash.com/photo-1449844908441-8829872d2607?q=80&w=1200",
    title: "Chalé da Serra",
    city: "Gramado",
    state: "RS",
    country: "Brasil",
    pricePerNight: 750,
    rating: 4.9,
    reviewsCount: 88,
    type: "chalet",
    isAvailable: false,
    bedrooms: 3,
    guests: 6,
    amenities: ["Lareira", "Wi-Fi", "Cozinha"]
  },
  {
    id: "3",
    imageUrl: "https://images.unsplash.com/photo-1502005229762-cf1b2da7c0e5?q=80&w=1200",
    title: "Casa Pé na Areia",
    city: "Ubatuba",
    state: "SP",
    country: "Brasil",
    pricePerNight: 1200,
    rating: 4.6,
    reviewsCount: 64,
    type: "house",
    isAvailable: true,
    bedrooms: 4,
    guests: 8,
    amenities: ["Piscina", "Churrasqueira", "Wi-Fi"]
  },
  {
    id: "4",
    imageUrl: "https://images.unsplash.com/photo-1460317442991-0ec209397118?q=80&w=1200",
    title: "Cabana do Lago",
    city: "Capitólio",
    state: "MG",
    country: "Brasil",
    pricePerNight: 350,
    rating: 4.3,
    reviewsCount: 41,
    type: "cabin",
    isAvailable: true,
    bedrooms: 1,
    guests: 2,
    amenities: ["Vista", "Cozinha"]
  },
  {
    id: "5",
    imageUrl: "https://images.unsplash.com/photo-1484154218962-a197022b5858?q=80&w=1200",
    title: "Flat Centro",
    city: "São Paulo",
    state: "SP",
    country: "Brasil",
    pricePerNight: 260,
    rating: 4.1,
    reviewsCount: 210,
    type: "flat",
    isAvailable: false,
    bedrooms: 1,
    guests: 2,
    amenities: ["Wi-Fi", "Academia"]
  }
];
